### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by phmanet** [ztc1997/ikuai-bypass#4]
登陆失败： Post "http://192.168.1.1/Action/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by GREENzgsh** [comment]
一样

**Comment by GREENzgsh** [comment]
> 登陆失败： Post “http://192.168.1.1/Action/login”： context deadline exceeded （Client.Timeout exceeded while awaiting headers）

网络接口里选一个和爱快的lan不冲突的网段，爱快的docker好像没法桥接使用本机地址
